let project = new Project('New Project');
project.addAssets('Assets/**');
project.addShaders('Shaders/**');
project.addSources('Sources');
project.addLibrary('zui');
// project.targetOptions.html5.disableContextMenu = true;
// project.targetOptions.html5.canvasId = 'my-custom-canvas-id';
// project.targetOptions.html5.scriptName = 'my-custom-script-name';
// project.targetOptions.html5.webgl = false;
resolve(project);
